services:
  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:8080"   # map le port 80 de l’hôte vers 8080 dans Nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: php_container
    volumes:
      - ./html:/usr/share/nginx/html
